### ISSUE TITLE
coveralls.detail filtering does not work as documented

### ISSUE THREAD

**Issue by flupke** [parroty/excoveralls#24] opened 2015-07-15 08:36 UTC
The docs say:
```
Also, displayed source code can be filtered by specifying arguments (it will be matched against the FILE column value).
```
But when you give a source file name it acts as if it was a test script:
```
$ mix coveralls.detail lib/stashex/parallel_jobs.ex                                                                                                                                                                                     (07-15 10:34)
lib/stashex/parallel_jobs.ex:1: warning: redefining module Stashex.ParallelJobs
lib/stashex/parallel_jobs.ex:8: warning: redefining module Stashex.ParallelJobs.State
lib/stashex/parallel_jobs.ex:142: warning: default arguments in run_job/3 are never used


Finished in 0.1 seconds (0.1s on load, 0.00s on tests)
0 tests, 0 failures

Randomized with seed 248648
----------------
COV    FILE                                        LINES RELEVANT   MISSED
  0.0% lib/mix/tasks/stashex.load_test.ex            188       58       58
 83.3% lib/stashex.ex                                 35        6        1
  0.0% lib/stashex/cache.ex                           61       15       15
 20.6% lib/stashex/cache_cleaner.ex                  103       34       27
  0.0% lib/stashex/cluster/dummy.ex                    8        0        0
  0.0% lib/stashex/cluster/ec2.ex                    136       23       23
 57.4% lib/stashex/cluster/server.ex                 192       54       23
100.0% lib/stashex/cluster/static.ex                  15        4        0
  0.0% lib/stashex/download.ex                       161       36       36
  0.0% lib/stashex/download_hub.ex                    50        8        8
  0.0% lib/stashex/endpoint.ex                        19        0        0
  0.0% lib/stashex/utils/http.ex                      39       10       10
 18.2% lib/stashex/utils/phoenix.ex                   58       11        9
  0.0% lib/stashex/utils/random.ex                    13        2        2
  0.0% web/controllers/cache_controller.ex            63       11       11
  0.0% web/controllers/info_controller.ex             19        2        2
  0.0% web/controllers/stashy_controller.ex           31        6        6
  0.0% web/router.ex                                  14        0        0
  0.0% web/views/error_view.ex                        17        1        1
  0.0% web/web.ex                                     48        1        1
[TOTAL]  17.4%
----------------
```
And when you give it the test script file, it runs the tests but does not show the detailed coverage informations:
```
$ mix coveralls.detail test/stashex/parallel_jobs_test.exs                                                                                                                                                                              (07-15 10:34)
....

Finished in 0.05 seconds (0.04s on load, 0.01s on tests)
4 tests, 0 failures

Randomized with seed 546053
----------------
COV    FILE                                        LINES RELEVANT   MISSED
  0.0% lib/mix/tasks/stashex.load_test.ex            188       58       58
 83.3% lib/stashex.ex                                 35        6        1
  0.0% lib/stashex/cache.ex                           61       15       15
 20.6% lib/stashex/cache_cleaner.ex                  103       34       27
  0.0% lib/stashex/cluster/dummy.ex                    8        0        0
  0.0% lib/stashex/cluster/ec2.ex                    136       23       23
 57.4% lib/stashex/cluster/server.ex                 192       54       23
100.0% lib/stashex/cluster/static.ex                  15        4        0
  0.0% lib/stashex/download.ex                       161       36       36
  0.0% lib/stashex/download_hub.ex                    50        8        8
  0.0% lib/stashex/endpoint.ex                        19        0        0
 87.2% lib/stashex/parallel_jobs.ex                  173       47        6
  0.0% lib/stashex/utils/http.ex                      39       10       10
 18.2% lib/stashex/utils/phoenix.ex                   58       11        9
  0.0% lib/stashex/utils/random.ex                    13        2        2
  0.0% web/controllers/cache_controller.ex            63       11       11
  0.0% web/controllers/info_controller.ex             19        2        2
  0.0% web/controllers/stashy_controller.ex           31        6        6
  0.0% web/router.ex                                  14        0        0
  0.0% web/views/error_view.ex                        17        1        1
  0.0% web/web.ex                                     48        1        1
[TOTAL]  27.4%
----------------
```

**Comment by parroty** [comment] 2015-07-15 14:12
Thank you for the report. It seems like a regression after started passing mix arguments for #17...
It's interface change, but I'm wondering to make the filtering argument explicit like,

`mix coveralls.detail --filter lib/stashex/parallel_jobs.ex`

since it's conflicting the target test code (parallel_jobs_test.exs) as you have shown.

**Comment by flupke** [comment] 2015-07-15 16:13
`--filter` looks good to me

**Comment by parroty** [comment] 2015-07-15 23:05
Pushed as above. I appreciate if you could retry.

**Comment by parroty** [comment] 2015-07-17 11:10
I'm closing at the moment, but if you find any further issue, please reopen or open another one.

**Closed by parroty** 2015-07-17 11:10 UTC

**Comment by flupke** [comment] 2015-08-04 09:54
Sorry I missed the notification. --filter works as expected on my project, thanks!
